# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packges', models.CharField(max_length=30, null=True)),
                ('deploy_env', models.CharField(max_length=30, null=True)),
                ('deploy_ip', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('type', models.CharField(choices=[(b'0', 'java'), (b'1', '\u5176\u4ed6')], default=0, max_length=30, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('repository', models.CharField(default=b'', max_length=120, verbose_name='\u4ee3\u7801\u5e93\u5730\u5740')),
                ('repos_user', models.CharField(default=0, max_length=30, verbose_name='\u7528\u6237')),
                ('branches', models.CharField(default=b'Master', max_length=30, verbose_name='\u5206\u652f')),
                ('builder', models.CharField(max_length=120, null=True, verbose_name='\u67d0\u4fe1\u606f')),
                ('build_info_pom', models.CharField(max_length=30, null=True, verbose_name='pom\u4fe1\u606f')),
                ('bulid_info_param', models.CharField(max_length=120, null=True, verbose_name='\u6253\u5305\u53c2\u6570')),
                ('project_env', models.CharField(choices=[(b'0', 'dev\u6d4b\u8bd5\u73af\u5883'), (b'1', 'pre\u9884\u4e0a\u7ebf\u73af\u5883'), (b'2', 'pro\u7ebf\u4e0a\u73af\u5883')], default=0, max_length=30, verbose_name='\u73af\u5883')),
                ('dev_address', models.CharField(default=b'', max_length=256, verbose_name='dev\u6d4b\u8bd5\u73af\u5883')),
                ('pre_address', models.CharField(default=b'', max_length=256, verbose_name='pre\u9884\u4e0a\u7ebf\u73af\u5883')),
                ('pro_address', models.CharField(default=b'', max_length=256, verbose_name='pro\u7ebf\u4e0a\u73af\u5883')),
                ('status', models.CharField(default=b'', max_length=30, verbose_name='\u72b6\u6001')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('describe', models.CharField(default=b'', max_length=120, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_type', models.CharField(max_length=30, null=True)),
                ('oper_user', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=124, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ProjectInfo')),
            ],
        ),
    ]
