# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180305_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=b'', max_length=120, null=True)),
                ('filename', models.CharField(default=b'', max_length=120, null=True)),
                ('img', models.ImageField(default=b'', max_length=256, null=True, upload_to=b'')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default=b'', max_length=120, null=True)),
                ('dnsfiles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.DnsFiles')),
            ],
        ),
    ]
