# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, null=True, verbose_name='IP\u5730\u5740')),
                ('owner', models.CharField(default='', max_length=120, null=True, verbose_name='\u7ba1\u7406\u5458')),
                ('be_app', models.CharField(default=0, max_length=30, null=True, verbose_name='\u4e1a\u52a1\u7ebf')),
                ('os', models.CharField(default='', max_length=30, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('hostname', models.CharField(max_length=120, null=True, verbose_name='\u4e3b\u673a\u57df\u540d')),
                ('host_type', models.CharField(max_length=30, null=True, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('pyh_host', models.CharField(max_length=120, null=True, verbose_name='\u5bbf\u4e3b\u673a')),
                ('host_env', models.CharField(choices=[('0', 'dev\u6d4b\u8bd5\u73af\u5883'), ('1', 'pre\u9884\u4e0a\u7ebf\u73af\u5883'), ('2', 'pro\u7ebf\u4e0a\u73af\u5883')], default=0, max_length=30, verbose_name='\u8fd0\u884c\u73af\u5883')),
                ('is_del', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'active'), ('1', '')], max_length=30, null=0, verbose_name='\u72b6\u6001')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('res', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
