# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20180424_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployinfo',
            name='deploy_ip',
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='desc',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='host',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
