# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20180525_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployinfo',
            name='delta',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='deploy_env',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='desc',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='end_time',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='host',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='packges',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='star_time',
            field=models.CharField(default='', max_length=125, null=True),
        ),
    ]
