# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0013_auto_20180528_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='deploy_env',
            field=models.CharField(default='pro', max_length=30, null=True),
        ),
    ]
