# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0014_auto_20180528_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployinfo',
            name='deploy_project',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='deploy.ProjectInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
