# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_auto_20180528_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployinfo',
            name='deploy_project',
        ),
        migrations.RemoveField(
            model_name='deployinfo',
            name='user',
        ),
    ]
