# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_deployinfo_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=30, null=True)),
                ('status', models.BooleanField(verbose_name=False)),
                ('desc', models.CharField(default='', max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.ProjectInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='deployinfo',
            name='project',
        ),
    ]
