# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20180528_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployproject',
            name='package',
            field=models.CharField(default='', max_length=125, null=True),
        ),
    ]
