# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_dashboard', '\u63a7\u5236\u9762\u677f'), ('access_log', '\u65e5\u5fd7\u7ba1\u7406'), ('access_super_manage', '\u8d85\u7ea7\u7528\u6237'), ('access_user_manage', '\u7528\u6237\u7ba1\u7406'), ('access_role_manage', '\u89d2\u8272\u7ba1\u7406'), ('access_operate_role', '\u64cd\u4f5c\u89d2\u8272')),
            },
        ),
    ]
