# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('passport', '0003_auto_20180320_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={},
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='codename',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 20, 3, 29, 35, 379958, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='desc',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='name',
            field=models.CharField(default='', max_length=125),
        ),
    ]
