# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeployInfo',
        ),
        migrations.RemoveField(
            model_name='projectlog',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
        migrations.DeleteModel(
            name='ProjectLog',
        ),
    ]
