# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0002_auto_20180228_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=b'', max_length=120, null=True)),
                ('desc', models.CharField(default=b'', max_length=30, null=True)),
                ('status', models.CharField(default=b'', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DnsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default=b'', max_length=60, null=True)),
                ('desc', models.CharField(default=b'', max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dnsfiles',
            name='host',
            field=models.ManyToManyField(to='app01.DnsHost'),
        ),
    ]
