# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
