# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20180228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='describe',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dev_address',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='dev\u6d4b\u8bd5\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pre_address',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='pre\u9884\u4e0a\u7ebf\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_address',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='pro\u7ebf\u4e0a\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='repos_user',
            field=models.CharField(default=0, max_length=30, null=True, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='repository',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='\u4ee3\u7801\u5e93\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='status',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='\u72b6\u6001'),
        ),
    ]
