# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20180301_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_admin',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dev_address',
            field=models.CharField(default='', max_length=512, null=True, verbose_name='dev\u6d4b\u8bd5\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pre_address',
            field=models.CharField(default='', max_length=512, null=True, verbose_name='pre\u9884\u4e0a\u7ebf\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_address',
            field=models.CharField(default='', max_length=512, null=True, verbose_name='pro\u7ebf\u4e0a\u73af\u5883'),
        ),
    ]
