# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0004_auto_20180411_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostWithProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=120, null=True, verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='build_info_pom',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='builder',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='bulid_info_param',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='dev_address',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='pre_address',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='pro_address',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_env',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='repos_user',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='download_path',
            field=models.CharField(default=0, max_length=120, verbose_name='\u4e0b\u8f7d\u8def\u5f84'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='server_port',
            field=models.CharField(default=0, max_length=30, null=True, verbose_name='\u670d\u52a1\u7aef\u53e3'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostwithproject',
            name='project',
            field=models.ManyToManyField(to='deploy.ProjectInfo'),
        ),
    ]
