# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20180424_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='code',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
