# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20180424_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
