# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20180424_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='project_admin',
            new_name='server_path',
        ),
        migrations.AlterField(
            model_name='hostwithproject',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
