# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0009_auto_20180525_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployinfo',
            name='delta',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='end_time',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='star_time',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='deployinfo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='desc',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
