# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180411_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
