# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_accesscontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'permissions': (('access_dashboard', '\u63a7\u5236\u9762\u677f'), ('access_log', '\u65e5\u5fd7\u7ba1\u7406'), ('access_role_manage', '\u89d2\u8272\u7ba1\u7406'), ('access_user_manage', '\u7528\u6237\u7ba1\u7406'))},
        ),
    ]
