# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_auto_20180320_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='desc',
            field=models.CharField(default='', max_length=125, null=True),
        ),
    ]
