# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_groupextend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyPermissionsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=30, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
                ('status', models.CharField(default='', max_length=30, null=True)),
                ('desc', models.CharField(default='', max_length=125, null=True)),
                ('code', models.CharField(default='', max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
