# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0008_user2group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2group',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
