# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0009_user2group_is_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifypermissionslog',
            name='code',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='modifypermissionslog',
            name='desc',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modifypermissionslog',
            name='status',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modifypermissionslog',
            name='type',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
